name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (workspaces)
        run: npm install

      - name: Lint client
        run: npm --prefix client run lint

      - name: Build client
        run: npm run build:client

      - name: Smoke test server
        env:
          PORT: 5000
          CLIENT_ORIGIN: http://localhost:5173
        run: |
          node server/src/index.js &
          SERVER_PID=$!
          echo "Waiting for server..."
          for i in {1..20}; do
            if curl -fsS http://localhost:5000/health > /dev/null; then
              echo "Server is up"
              break
            fi
            sleep 1
          done
          curl -fsS http://localhost:5000/health
          kill $SERVER_PID

      - name: Upload client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist
