name: Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build:client

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist

      # Example deployment placeholder. Replace with your hosting provider.
      # - name: Deploy to Render/Heroku/Vercel
      #   run: |
      #     echo "Deploy using provider CLI or API here"
